### ISSUE TITLE
Sound garbled

### ISSUE THREAD

**Issue by muellert** [juha-h/baresip-studio#269]
Hi,

after upgrading to 34.0.0, I get the first few seconds of the call completely garbled sound, but on this phone number, I get only garbled sound and cannot understand a single thing:

0800 330 2202

This is a phone number in Germany, I'm don't know whether you can call it from outside of Germany.

I have already tried rebooting my phone, and I've tried a different SIP client (Linphone), with the result that the reboot did not help, and that Linphone doesn't have the problem. It has other problems, though, which brought me to baresip in the first place.

**Comment by juha-h** [comment]
If it is a regular PSTN number, you must be using a SIP/PSTN gateway somewhere.  Does calling a SIP endpoints, such as The Test Call, work OK?

Turn on SIP Trace in Settings and find out how the call is setup, for example, is there early media, and what codecs are used.

**Comment by muellert** [comment]
The 0800 number is a service number of a large carrier. It should be all VoIP in their network, as they are no longer offering no-VoIP connections since two years or so. Making the test call works ok, but eg. this call doesn't, and calling other people also results in the first few seconds being garbled.
I have configured nothing in terms of proxies, TURN or STUN servers, just the bare minimum to get baresip to register with my SIP provider (sipgate). Now that I have produced such a logfile, how can I give you the info you need, and what can or should I trim from the file? It's 132kb large for a few seconds of call.

**Comment by juha-h** [comment]
Where have you installed 34.0.0 from (Play Store or F-Droid)?

What is Request URI of the call (in INVITE request)?  I could try if I can call it.

Regarding logfile, you should filter the file so that it contains only lines with word 'Baresip'.   Then it would be much smaller. If you don't mind sharing details of the call, you can email the whole file to me.  My email address is on the About page.

After 33.2.0 there has been some changes in baresip lib that may affect early media.  Baresip Android app has not had any such changes that could cause your issue.

**Comment by juha-h** [comment]
I found the cause.  It is a bug in baresip library.  Will create a new version of baresip app once the bug has been fixed.

**Comment by juha-h** [comment]
This issue should now be fixed in version 34.1.0 of baresip+ app and in 47.10 of baresip app.  It takes several days before those are available in F-Droid.

If you want to try, I placed 34.1.0 available in https://box.tutpro.com/tmp/baresip+.apk.  Most likely you need to save your configuration before install and then restore after.

**Comment by juha-h** [comment]
34.1.0 is now available on F-Droid.  Re-open is the issue still remains.

**Comment by muellert** [comment]
i have taken a backup of the old data, then upgraded to 34.1.0, then rebooted the phone. The problem persists, except that now, it also take 20-30 seconds before the call is being established.

**Comment by juha-h** [comment]
Perhaps your issue was not related to early audio.   I just tried with 34.1.0, and there was no delay when I called The Test Call and audio worked fine.   Also early audio worked OK.
