### ISSUE TITLE
Problem with Speakerphone Key and freezes

### ISSUE THREAD

**Issue by morty303** [juha-h/baresip-studio#530]
hello,
the latest updates after version 63.2.0 (410) always freezes my speakerphone key and also shutdown freezes baresip app with delay.
only version 63.2.0 (410) still works.

best regards

**Comment by juha-h** [comment]
Sorry about that. Latest is 63.2.5.  Does also that have these issues?

**Comment by morty303** [comment]
> Sorry about that. Latest is 63.2.5. Does also that have these issues? I just tried with 63.2.5 and it worked OK.

hi and sorry for late reply.
just updated my fdroid baersip release to 63.2.5.
when i press during a call the speakerphone key it needs some seconds. it looks like it want to freeze.
when i want to stop a call and press red phone icon it needs also some seconds and looks like it want to freeze.
also, when i speak, the other didnt hear my voice.

in all releases to 63.2.0  the others say that they hear themselve with echo.

some other question.
do you get the letter # instead %23 work?

best regards

**Comment by morty303** [comment]
where can i download old 3.2.0 release?
fdroid has only 3.2.3 what didnt work.

**Comment by morty303** [comment]
can you add in baresipsetings a button to hide the chat?
my  phone provider didnt allow that. would be nice if i can hide the chat from menu. ;)

**Comment by juha-h** [comment]
morty303 writes:

> can you add in baresipsetings a button to hide the chat?
> my  phone provider didnt allow that. would be nice if i can hide the
> chat from menu. ;)

This is a very strange feature request.  Phone provider should have
nothing to do with the apps their customers are using.

**Comment by juha-h** [comment]
morty303 writes:

> where can i download old 3.2.0 release?
> fdroid has only 3.2.3 what didnt work.

3.2.0 is not anymore available in my repositories.  I went though the
commits from 3.2.0 to 3.2.3 and didn't find anything that could effect
speakerphone key or freezes.

**Comment by juha-h** [comment]
I can't reproduce the freeze issues on my devices.  Do not report many issues in the same issue. What do you mean by "do you get the letter # instead %23 work?"

**Comment by morty303** [comment]
> morty303 writes:
>  can you add in baresipsetings a button to hide the chat?
>  my  phone provider didnt allow that. would be nice if i can hide the
>  chat from menu. ;)
> This is a very strange feature request.  Phone provider should have
> nothing to do with the apps their customers are using.

i don' t understand how the chat work. i only have added my provider settings to make landline calls. do i need a registered provider to chat via baresip?

**Comment by morty303** [comment]
> Sorry about that. Latest is 63.2.5. Does also that have these issues? I just tried with 63.2.5 and it worked OK.

hmmmm, only 63.2.0 works for me. in  all releases after this the others didnt hear my voice. so pity.

**Comment by morty303** [comment]
> morty303 writes:
>  where can i download old 3.2.0 release?
>  fdroid has only 3.2.3 what didnt work.
> 3.2.0 is not anymore available in my repositories.  I went though the
> commits from 3.2.0 to 3.2.3 and didn't find anything that could effect
> speakerphone key or freezes.

i found a backup from 63.2.0 on my usb stick.  the speakerphonekey don't freeze there. i hope your next update will work fine.

**Comment by morty303** [comment]
> morty303 writes:
>  can you add in baresipsetings a button to hide the chat?
>  my  phone provider didnt allow that. would be nice if i can hide the
>  chat from menu. ;)
> This is a very strange feature request.  Phone provider should have
> nothing to do with the apps their customers are using.

thx for info. perhaps you can hide it in future. ;)

**Comment by morty303** [comment]
> I can't reproduce the freeze issues on my devices. Do not report many issues in the same issue. What do you mean by "do you get the letter # instead %23 work?"

when i want to hide my number i must  use:
*31#(iutgoing number)
baresip shows error: invalid sip or tel url
baresip didn't know the charakter #
i need to use:
*31%23(outgoing number)
also when i want to make a call with my second or third landline number.
i need to use:
*122#(outgoing number)
*123#(outgoing number)
same error.
*122%23(outgoing number) works
*123#%23(outgoing number) works

**Comment by juha-h** [comment]
This should now work after commit https://github.com/juha-h/baresip-studio/commit/d5f3661b6f7adb43b8dd265ddec2950ce1ca5460.

See Wiki/Debugging regarding the other issues.

**Comment by morty303** [comment]
hello again, in 63.3.0 the  speaker phone key still freezes when i press it during a call.
also sound dropouts comes.

**Comment by juha-h** [comment]
I cannot repeat the issues on my device. You need to provide the logs as described here https://github.com/juha-h/baresip-studio/wiki/Debugging.

**Comment by juha-h** [comment]
I'll close this since there is nothing I can do without further information.
